### PR TITLE
Updating the Microsoft.NET.Test.Sdk to a newer version

### PR DESCRIPTION
**Pull request by ahsonkhan**
- This resolves the VS issue and now all tests run in VS.

You should now be able to click Run All Tests in the Test Explorer and they will run to completion rather than aborting mid way (especially for System.Buffers.Experimental.Tests).

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
Thanks. Looks good.

**Comment by ahsonkhan** [comment]
Please let me know if you get "Test aborted" errors after this change. I got the "fix" but the root cause was unknown so if it occurs again, I will chase the VS Unit Test team again (after the VS 2017 release).

**Comment by ahsonkhan** [comment]
> Please let me know if you get "Test aborted" errors after this change. I got the "fix" but the root cause was unknown so if it occurs again, I will chase the VS Unit Test team again (after the VS 2017 release).

cc @shiftylogic

**Comment by ahsonkhan** [comment]
Partially fixes #1155

**Pull request merged**
