### PR TITLE
Some improvements in Utf8String

### PR DESCRIPTION
**Pull request by krwq**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
Did you measure before and after perf?

**Comment by krwq** [comment]
I didn't change any logic for the perf to improve or get worse, just removed code duplicate

**Comment by krwq** [comment]
I just measured and it seems like I got some regression. Let me investigate

**Comment by KrzysztofCwalina** [comment]
What are we doing with this?

**Comment by KrzysztofCwalina** [comment]
@krwq, ping!

**Comment by krwq** [comment]
I'm closing for now. I'll come back to it or rewrite from the scratch. I'd like to increase perf of Utf8String and this PR obviously doesn't help.

**Pull request closed without merging**
