### PR TITLE
Remove 16 bytes from BufferSegment

### PR DESCRIPTION
**Pull request by benaadams**
Not sure caching memory here does much? Always calling it once and stashing, vs calling very light .ctor on use and inlining it?

/cc @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
Need to see how this affects Kestrel. Originally this showed up on the profile but we have since then gone through lots of iterations...

**Comment by benaadams** [comment]
Used to have the check on owner so was much more expensive

**Comment by KrzysztofCwalina** [comment]
Given BufferSegment is a class, do you think these 16 bytes matter?

**Comment by benaadams** [comment]
Is allocated for every request; so increases the likelyhood the GC will become interested

**Comment by benaadams** [comment]
Is allocated for every request (read); so increases the likelyhood the GC will become interested; if its not adding benefit is there a need for it?

**Comment by KrzysztofCwalina** [comment]
If they are not adding benefits, we should of course not have them (the 16 bytes).

**Comment by davidfowl** [comment]
I'd like to re-measure with this change.

**Comment by davidfowl** [comment]
I think this would make the perf of writing worse.

**Pull request closed without merging**
