### PR TITLE
Fix conditionally compiled Debug.Assert

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Comment by shiftylogic** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test

**Comment by ahsonkhan** [comment]
Are there other using directives that we may need back because of conditionally compiled code?

**Some were cleaned up here:**
https://github.com/dotnet/corefxlab/pull/1281
https://github.com/dotnet/corefxlab/pull/1507

**Comment by pakrym** [comment]
@halter73 why do we care about master? We consume code from aspnetcore branch and nobody except use merges there. What broke and when?

**Comment by halter73** [comment]
Kestrel.Transport.Abstractions doesn't compile with BLOCK_LEASE_TRACKING. With this change, it does. I didn't look into which branch we clone for our CoreFxLab.Sources package. I can rebase this.

**Comment by halter73** [comment]
Also, if we're worried that the usings might just get removed again, we can instead use `global::System.Diagnostics...` inside of conditionally compiled sections.

**Comment by halter73** [comment]
This is subsumed by #1601

**Pull request closed without merging**
