### PR TITLE
Lowering stdlib version of System.Slices

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@livarcocc, @piotrpMSFT, @sokket, @weshaggard 

I would like to lower versions of all projects in corfxlab, but this will take a week or so because we don't support cross-project dependencies. And so if I lower them all at once, the repo does not build as higher level components don't find lower version packages (dependencies) on myget. This is ridiculous.

**Comment by davidfowl** [comment]
Don't support cross project dependencies ?

**Comment by KrzysztofCwalina** [comment]
Yeah, I was told the new dotnet.exe based build system does not support cross-project dependencies

**Comment by sokket** [comment]
LGTM

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
