### PR TITLE
Update DNX and lock files

### PR DESCRIPTION
**Pull request by terrajobst**
@KrzysztofCwalina, this fixes this error:

```
error CS0731: The type forwarder for type 'System.Diagnostics.CodeAnalysis.SuppressMessageAttribute' in assembly 'mscorlib' causes a cycle
```

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
Thanks for doing the tools update. I am not great at reading computer generated files, but a cursory scan of the changes looks good. :-)
Ship it!

**Comment by davidfowl** [comment]
Lock files shouldn't be checked in.....

**Comment by terrajobst** [comment]
@davidfowl Ha! :-) I just asked @ericstj what we should do and he said I should check them in and lock them.

So what's the recommendation?

**Comment by davidfowl** [comment]
Never check them in. We're going to be removing the lock: true soon as well. Going to have to prepare core fx for that change

**Comment by ericstj** [comment]
Right now we have to do this if we are using *'s in the project.json.  Otherwise you build and it may fail depending on what's in the feed (as you found with the un-locked files).
David is suggesting we stop using *s and don't check in the lock files.  I think that can be done later.  Ideally after we have some sort of tooling in DNX/Nuget to accomplish the equivalent scenario.

**Comment by ericstj** [comment]
LGTM

**Comment by terrajobst** [comment]
OK, then I'll simply follow what CoreFX does today. Thanks @davidfowl and @ericstj!

**Comment by davidfowl** [comment]
Sure but labs doesn't float versions.... :)

**Comment by ericstj** [comment]
Yeah it does: https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/src/project.json

**Comment by weshaggard** [comment]
I agree we must keep the lock files locked and checked when using * versions. 

@davidfowl once you guys remove the support for locked lock files are there plans to provide some mechanisms to update large sets of project.json files to newer versions? On top of that I assume you will no longer use lock in the name and provide a way to generate them outside of the source tree.

**Pull request merged**
