### PR TITLE
Change folder structure

### PR DESCRIPTION
**Pull request by livarcocc**
Moving all projects under their own folder under src and the tests under their own test project under tests.

Updating project.json to reflect the new folder structure. Also, incremental building is not working, so I had to turn off parallel building in MSBuild. Lastly, I removed dotnet pack for the test projects so that they are not published to the myget feed.

Adding a corefxlab.sln file and removing the individual solutions under the individual projects.

### CODE REVIEW

**Comment by omariom** [comment]
With all the recent changes what is the way to run tests?

**Comment by livarcocc** [comment]
go to a test project, dotnet restore, if you haven't already. Then do dotnet build, if you haven't already or if you made changes, and then do dotnet test. That's it.

**Comment by omariom** [comment]
@livarcocc  Thanks!

**Comment by livarcocc** [comment]
@dotnet-bot Test Windows Release please

**Pull request merged**
