### PR TITLE
New toolset compiler

### PR DESCRIPTION
**Pull request by VSadov**
This build brings "poisoning". Some new features will now produce code in a way that would prevent accidental/unsafe use by old compilers.

The VSIX is:
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6182608.vsix

### CODE REVIEW

**Comment by VSadov** [comment]
Test Innerloop Ubuntu16.04 Debug Build and Test please

**Comment by VSadov** [comment]
retest this please

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test Innerloop Ubuntu16.04 Release Build and Test please

**Comment by VSadov** [comment]
test Innerloop OSX10.12 Release Build and Test please

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test

**Pull request merged**
