### PR TITLE
Cleaned up UInt32 parsing APIs

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
Trying to settle on the shape of the parsing APIs. This is the first stab implementing uint parsing.

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@sokket could you take a look?

**Comment by omariom** [comment]
Now when there is ReadOnlySpan shouldn't it be used in public API?  Where appropriate.

**Comment by KrzysztofCwalina** [comment]
Good point. I will update to ROSpan

**Comment by sokket** [comment]
LGTM

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
