### PR TITLE
Stopped doing dnu restore and replaced it with dotnet restore

### PR DESCRIPTION
**Pull request by livarcocc**
cc @KrzysztofCwalina

### CODE REVIEW

**Comment by livarcocc** [comment]
@dotnet-bot Test this please

**Comment by KrzysztofCwalina** [comment]
looks good.

**Comment by livarcocc** [comment]
@mmitche This one is stuck for 18 hours.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by livarcocc** [comment]
@dotnet-bot test this please

**Pull request merged**
