### PR TITLE
Pipe: complete writerAwaitable based on examined instead of consumed bytes

### PR DESCRIPTION
**Pull request by tmds**
Implements https://github.com/dotnet/corefxlab/issues/1355

### CODE REVIEW

**Comment by davidfowl** [comment]
Few things:
- I'm not sure we want this.
- This is an extremely hot path and this it looks like we're computing the length for both consumed and examined every time. Did you run the micro benchmarks to see how this affects throughput?

**Comment by tmds** [comment]
> I'm not sure we want this.
> This is an extremely hot path and this it looks like we're computing the length for both consumed and examined every time. Did you run the micro benchmarks to see how this affects throughput?
> You don't have any tests.

Let's figure out first if it is needed.

**Comment by tmds** [comment]
> This is an extremely hot path and this it looks like we're computing the length for both consumed and examined every time.

I've optimized it a bit already, taking into account that examined >= consumed. Also consumed and examined will be in the same segment most of the time so `consumed.GetLength(examined)` will be in the inlined case.

**Comment by davidfowl** [comment]
> I've optimized it a bit already, taking into account that examined >= consumed. Also consumed and examined will be in the same segment most of the time so consumed.GetLength(examined) will be in the inlined case.

Where are the before and after benchmarks? And the unit tests.

**Comment by ahsonkhan** [comment]
> Where are the before and after benchmarks? And the unit tests.

@tmds, please update the PR.

**Comment by davidfowl** [comment]
We decided not to take this

**Pull request closed without merging**
