### PR TITLE
Updating to a new CLI + CoreFx assemblies

### PR DESCRIPTION
**Pull request by shiftylogic**
* Had to patch all string.AsSpan calls to use string.AsReadOnlySpan now.
* We are forced to include a specific runtime version as a temporary workaround to out-of-sync issues with CLI, core-setup, and CoreFx (see bugs dotnet/cli#7157 and dotnet/corefx#23116).
* A side-effect of the above workaround is that the 2 projects that targeted netcoreapp1.1 needed to change to 2.0 to fix a run-time issue.
* All projects should be re-targeted to 2.1 once the above bugs are resolved.
* I also updated the "update-dependencies" tool so that Maestro will keep the runtime version in-sync with the CoreFx assemblies and CLI. In theory, PRs posted by Maestro should merge and build clean now.

### CODE REVIEW

**Comment by shiftylogic** [comment]
@ahsonkhan @KrzysztofCwalina @joshfree

**Comment by KrzysztofCwalina** [comment]
looks good

**Comment by ahsonkhan** [comment]
> A side-effect of the above workaround is that the 2 projects that targeted netcoreapp1.1 needed to change to 2.0 to fix a run-time issue.

What about VS test discovery?
https://github.com/dotnet/corefxlab/pull/1692#discussion_r132338457

**Comment by shiftylogic** [comment]
No idea. I don't tend to use VS. I suspect they disappear like our other tests. I could have solved this with extra work and flags in the project files. I'm hoping this workaround is only temporary (on the order of a couple weeks).

At a macro level, test discovery needs to be debugged and solved anyways.

**Pull request merged**
