### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by davidfowl**
We're experiencing hangs and test aborts on the CI, the goal is to narrow down which tests are problematic.

### CODE REVIEW

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
Hangs found and fixed

**Pull request closed without merging**
