### PR TITLE
Updates to ILSub

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
These updates are a prerequisite to #534 
I just took the tool sources from the PR, and built the exe. 
It has been reviewed previously by @krwq

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@krwq, @omariom

**Comment by omariom** [comment]
This is my first **LGTM** on a public repository )

**Comment by KrzysztofCwalina** [comment]
@omariom, it's good to have a high bar for LGMTing PRs :-)

**Comment by KrzysztofCwalina** [comment]
...and for the record/context, @omariom wrote the code :-)

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
