### PR TITLE
Several fixes

### PR DESCRIPTION
**Pull request by davidfowl**
- Support pipelined http requests in the sample parser
- Added Default to TaskRunScheduler
- Fixes to libuv transport

### CODE REVIEW

**Comment by pakrym** [comment]
LGTM

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
@dotnet-bot test Windows Release please

**Comment by davidfowl** [comment]
@dotnet-bot test this please

**Comment by davidfowl** [comment]
Merging with these methods skipped. Will try to isolate the hangs.

**Pull request merged**
