### PR TITLE
Update exit from help output and app name

### PR DESCRIPTION
**Pull request by russellhadley**
After printing the help screen System.CommandLine was calling fastfail which tears down the process with an exception.  This caused a popup and looked like an exceptional exit.  Switched the code to use Environment.Exit(), which is now available.  At the same time I also include the code to call Environment.GetCommandLineArgs() to allow the help code to find the app name.

### CODE REVIEW

**Comment by russellhadley** [comment]
@KrzysztofCwalina @terrajobst PTAL

**Comment by KrzysztofCwalina** [comment]
Any tests need to be updated to test the new behavior?

**Comment by russellhadley** [comment]
@KrzysztofCwalina there are already tests that check this functionality I just removed the #ifdef so that the functionality would be available for dnxcore.  We should be able to run these tests other ways  (actually I'd like to see a build I can run on OSX or Linux for instance) but changing the automation is a bit beyond me.  Who is doing the CI for this stuff?

**Comment by KrzysztofCwalina** [comment]
cc: @terrajobst, @piotrpMSFT 

Looks good to me.

**Comment by terrajobst** [comment]
Thanks for fixing this!

**Pull request merged**
