### PR TITLE
Chasing the bug [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test

**Comment by joshfree** [comment]
Would it be helpful to have access to a Mac out of the machine pool to be able to just run this in a loop?

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by joshfree** [comment]
OK I'm getting you a MBP for this ;)

**Pull request closed without merging**
