### PR TITLE
Remove Brotli from Corefxlab

### PR DESCRIPTION
**Pull request by ianhays**
cc: @ahsonkhan

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @dotnet/corefxlab-contrib

**Comment by sundarchi1** [comment]
Removed?! Why?
Is Brotli finally production ready in the upcoming .NET 4.7.2?

**Comment by ahsonkhan** [comment]
It is available for preview in .NET Core 2.1: https://github.com/dotnet/corefx/tree/master/src/System.IO.Compression.Brotli.

**Comment by ahsonkhan** [comment]
@ianhays, can you please remove System.IO.Compression.Tests from the PerfHarness?
https://github.com/dotnet/corefxlab/blob/master/scripts/PerfHarness/PerfHarness.csproj#L17

**Pull request merged**
