### PR TITLE
Update UTF-8 JsonWriter APIs based on 2nd API feedback

### PR DESCRIPTION
**Pull request by ahsonkhan**
Addressing most of https://github.com/dotnet/apireviews/pull/82

- Removed MaxDepth from JsonWriterState
- Set max depth allowed to `1_000`
- Rename WriteValue to WriteNumberValue, WriteStringValue, etc.
- Add `bool suppressEscaping` optional argument to all APIs that take "strings" (either as property name or value). The default is false (i.e. we escape everything).
- Changed validation to only do structural validation
- JsonWriter is no longer generic.
- Renamed Formatted to Indented

**TODO:**
- [ ] Implement escaping logic
- [ ] Check if the span returned from `IBufferWriter<byte>` is large enough

### CODE REVIEW

**Comment by ahsonkhan** [comment]
```C#
namespace System.Text.Json {
    public sealed class JsonWriterException : Exception {
        public JsonWriterException(string message);
    }
    public struct JsonWriterOptions {
        public bool Indented { get; set; }
        public bool SkipValidation { get; set; }
    }
    public struct JsonWriterState {
        public JsonWriterState(JsonWriterOptions options = default(JsonWriterOptions));
        public long BytesCommitted { get; }
        public long BytesWritten { get; }
        public JsonWriterOptions Options { get; }
    }
    public ref struct Utf8JsonWriter {
        public Utf8JsonWriter(IBufferWriter<byte> bufferWriter, JsonWriterState state = default(JsonWriterState));
        public Utf8JsonWriter(Span<byte> outputSpan, JsonWriterState state = default(JsonWriterState));
        public long BytesCommitted { get; }
        public long BytesWritten { get; }
        public int CurrentDepth { get; }
        public JsonWriterState CurrentState { get; }
        public void Flush(bool isFinalBlock = true);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<DateTime> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<DateTimeOffset> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<decimal> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<double> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<Guid> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<int> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<long> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<float> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<uint> values, bool suppressEscaping = false);
        public void WriteArray(ReadOnlySpan<byte> propertyName, ReadOnlySpan<ulong> values, bool suppressEscaping = false);
        public void WriteBoolean(ReadOnlySpan<byte> propertyName, bool value, bool suppressEscaping = false);
        public void WriteBoolean(ReadOnlySpan<char> propertyName, bool value, bool suppressEscaping = false);
        public void WriteBoolean(string propertyName, bool value, bool suppressEscaping = false);
        public void WriteBooleanValue(bool value);
        public void WriteCommentValue(ReadOnlySpan<byte> utf8Text, bool suppressEscaping = false);
        public void WriteCommentValue(ReadOnlySpan<char> utf16Text, bool suppressEscaping = false);
        public void WriteCommentValue(string utf16Text, bool suppressEscaping = false);
        public void WriteEndArray();
        public void WriteEndObject();
        public void WriteNull(ReadOnlySpan<byte> propertyName, bool suppressEscaping = false);
        public void WriteNull(ReadOnlySpan<char> propertyName, bool suppressEscaping = false);
        public void WriteNull(string propertyName, bool suppressEscaping = false);
        public void WriteNullValue();
        public void WriteNumber(ReadOnlySpan<byte> propertyName, decimal value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, double value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, int value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, long value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, float value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, uint value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<byte> propertyName, ulong value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, decimal value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, double value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, int value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, long value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, float value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, uint value, bool suppressEscaping = false);
        public void WriteNumber(ReadOnlySpan<char> propertyName, ulong value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, decimal value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, double value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, int value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, long value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, float value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, uint value, bool suppressEscaping = false);
        public void WriteNumber(string propertyName, ulong value, bool suppressEscaping = false);
        public void WriteNumberValue(decimal value);
        public void WriteNumberValue(double value);
        public void WriteNumberValue(int value);
        public void WriteNumberValue(long value);
        public void WriteNumberValue(float value);
        public void WriteNumberValue(uint value);
        public void WriteNumberValue(ulong value);
        public void WriteStartArray();
        public void WriteStartArray(ReadOnlySpan<byte> propertyName, bool suppressEscaping = false);
        public void WriteStartArray(ReadOnlySpan<char> propertyName, bool suppressEscaping = false);
        public void WriteStartArray(string propertyName, bool suppressEscaping = false);
        public void WriteStartObject();
        public void WriteStartObject(ReadOnlySpan<byte> propertyName, bool suppressEscaping = false);
        public void WriteStartObject(ReadOnlySpan<char> propertyName, bool suppressEscaping = false);
        public void WriteStartObject(string propertyName, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, DateTime value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, DateTimeOffset value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, Guid value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, ReadOnlySpan<byte> value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, ReadOnlySpan<char> value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<byte> propertyName, string value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, DateTime value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, DateTimeOffset value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, Guid value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, ReadOnlySpan<byte> value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, ReadOnlySpan<char> value, bool suppressEscaping = false);
        public void WriteString(ReadOnlySpan<char> propertyName, string value, bool suppressEscaping = false);
        public void WriteString(string propertyName, DateTime value, bool suppressEscaping = false);
        public void WriteString(string propertyName, DateTimeOffset value, bool suppressEscaping = false);
        public void WriteString(string propertyName, Guid value, bool suppressEscaping = false);
        public void WriteString(string propertyName, ReadOnlySpan<byte> value, bool suppressEscaping = false);
        public void WriteString(string propertyName, ReadOnlySpan<char> value, bool suppressEscaping = false);
        public void WriteString(string propertyName, string value, bool suppressEscaping = false);
        public void WriteStringValue(DateTime value);
        public void WriteStringValue(DateTimeOffset value);
        public void WriteStringValue(Guid value);
        public void WriteStringValue(ReadOnlySpan<byte> utf8Text, bool suppressEscaping = false);
        public void WriteStringValue(ReadOnlySpan<char> utf16Text, bool suppressEscaping = false);
        public void WriteStringValue(string utf16Text, bool suppressEscaping = false);
    }
    public static class Utf8JsonWriterHelpers {
        public static OperationStatus EscapeString(ReadOnlySpan<byte> value, Span<byte> destination, out int consumed, out int bytesWritten);
        public static OperationStatus EscapeString(ReadOnlySpan<char> value, Span<byte> destination, out int consumed, out int bytesWritten);
        public static OperationStatus EscapeString(string value, Span<byte> destination, out int consumed, out int bytesWritten);
    }
}
```

**Comment by KrzysztofCwalina** [comment]
Are the Utf8JsonWriterHelpers methods extensions? If not, why are they on a separate type? i.e. why are they not static methods on the writer?

**Comment by ahsonkhan** [comment]
> Are the Utf8JsonWriterHelpers methods extensions? If not, why are they on a separate type? i.e. why are they not static methods on the writer?

Good point. They should be on the writer itself. Regardless, I am removing these for now and deferring adding them as public surface area to the JsonWriter after the `TextEncoder` issue is resolved (i.e. https://github.com/dotnet/corefx/issues/33509). Ideally, the escaping helper wouldn't live here, especially if someone wants to override the escaping logic.

cc @GrabYourPitchforks

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Pull request merged**
