### PR TITLE
Sort ProjectReferences alphabetically

### PR DESCRIPTION
**Pull request by kant2002**
This address small nit picking from #2333

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by kant2002** [comment]
@ahsonkhan is I also possible to ask bot to do some tasks, or this is MSFT only?

**Comment by ahsonkhan** [comment]
> @ahsonkhan is I also possible to ask bot to do some tasks, or this is MSFT only?

I believe any collaborator can do it. Try dotnet-bot help.

**Pull request merged**
