### PR TITLE
Update xunit.perf to newer version and update README

### PR DESCRIPTION
**Pull request by ahsonkhan**
We get capabilities to collect new metrics (and customize which metrics we want to see) with the latest package of xunit.performance.

Example:
> --perf:collect default+BranchMispredictions+CacheMisses+InstructionRetired+gcapi

cc @jorive, @KrzysztofCwalina

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
Does it make sense to update the run.bat file too?

**Comment by ahsonkhan** [comment]
> Does it make sense to update the run.bat file too?

Update the folder path to dotnetcli? That was done here: https://github.com/dotnet/corefxlab/pull/1872/files

Or are you suggesting adding the extra metrics to run.bat? If so, which ones would you like to see?

**Comment by KrzysztofCwalina** [comment]
What are the default metrics we collect?

**Comment by ahsonkhan** [comment]
> What are the default metrics we collect?

According to the README [here](https://github.com/Microsoft/xunit-performance), the default is Duration only (which is always enabled) along with any metrics specified in the test source.

> --perf:collect default
 Collect metrics specified in the test source code by using xUnit Performance API attributes

**Comment by KrzysztofCwalina** [comment]
I added instructions retired and cache misses to run.bat in some other PR.
Thanks!

**Pull request merged**
