### PR TITLE
Add WriteCsv method (plus unit tests). This solves #2917.

### PR DESCRIPTION
**Pull request by dcostea**
In my work with DataFrame I need to save the new data to csv file, so I think we can have WriteCsv. This pairs nicely with LoadCsv (I tried to stick to conventions used there) and it solves #2917, as well.

I have added a few unit tests.

Still, this is an idea and I'm open to suggestions.

@pgovind @eerhardt, what do you think?

### CODE REVIEW

**Comment by eerhardt** [comment]
@dcostea - can you rebase this change on the latest master? I'm still seeing a bunch of the changes from #2933.

**Comment by dcostea** [comment]
> @dcostea - can you rebase this change on the latest master? I'm still seeing a bunch of the changes from #2933.

@eerhardt I'm not very good with git fork (still learning), can you please confirm me the next operation?
```
git fetch upstream
git rebase upstream/master
```

**Comment by eerhardt** [comment]
Part of the problem is that you are using your `master` branch on your fork to make proposed changes. Everyone has their own local dev process, but what I typically do is:

1. Never commit to my local `master` branch. This branch only takes changes from the `upstream` remote.
2. In `master` - `git pull` to get all the latest changes.
3. `git checkout -b SomeNewBranchName`
4. `git commit` any changes
5. `git push` to push the `SomeNewBranchName` branch to my fork

and make the PR from there. Then when starting on a new PR, start the process over - get on the `master` branch and `git pull` the latest `upstream/master` changes, create a new branch, etc.

Since you already have a `merge` commit in your history above, it isn't going to be easy to fix. My suggestion would be to do the above process (starting with a clean `master` branch that is in sync with upstream). And then cherry-pick the f7bab65 commit into that branch. That way you only have a single commit on top of what is in master.

**Comment by dcostea** [comment]
That makes sense. Thank you!

**Comment by dcostea** [comment]
I abandon this and reopen it.

**Pull request closed without merging**
