### PR TITLE
Remove netci.groovy now that we have azure devops ci

### PR DESCRIPTION
**Pull request by safern**
cc: @ahsonkhan @chcosta

### CODE REVIEW

**Comment by safern** [comment]
@dotnet-bot test ci please

**Comment by safern** [comment]
I guess once this is merged, the jobs shouldn't appear in consequent PRs?

**Comment by ahsonkhan** [comment]
Where's the CI job `Gen CI(dotnet-ci) - master/netci.groovy` coming from?

**Comment by safern** [comment]
From my `@dotnet-bot test ci please` comment. But it failed as expected since it didn't find the file.

**Pull request merged**
