### PR TITLE
Headers parser now supports multi-segment buffers

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
I went back to the original implementation using vectorized IndexOf. Initially I did not want to do it because I thought it would not be best for ReadOnlyBytes, but then it turns out it works quite well. The bonus is that now the implementation is very similar to the original implementation.

I added some handler overloads taking by ref handlers. This allows handlers to be structs.

All tests from https://github.com/aspnet/KestrelHttpServer/blob/200d8debc005bac2c15424b20c6b7bb4a50483cc/test/Microsoft.AspNetCore.Server.KestrelTests/HttpParserTests.cs except for skipped ParseHeadersConsumesBytesCorrectlyAtEnd test and logging test (logging is not supported) are passing. 
The skipped test is skipped because the semantics it tries to enforce are very strange. The parsing routine fails (returns false) yet the tests wants the parser to return non-zero consumedBytes.

The current perf results are pretty good. "Suffix "Rb" means ReadableBuffer, "Rob" means ReadOnlyBytes", and "Ref" means handler struct passed by ref.

     Test Name                         | Metric                | Iterations |    AVERAGE |    STDEV.S |        MIN |        MAX
    :--------------------------------- |:--------------------- |:----------:| ----------:| ----------:| ----------:| ----------:
     HttpParserBench.FullRequestLegacy | Duration              |    101     |     13.542 |      3.466 |     12.616 |     47.936
     HttpParserBench.FullRequestLegacy | Instructions Retired  |    101     | 8.944E+007 | 7.293E+006 | 8.850E+007 | 1.620E+008
     HttpParserBench.FullRequestLegacy | Branch Mispredictions |    101     |  11152.475 |  87817.168 |      0.000 | 8.847E+005
     HttpParserBench.FullRequestLegacy | Cache Misses          |    101     |   7380.911 |  31870.038 |      0.000 | 3.236E+005
     HttpParserBench.FullRequestRb     | Duration              |    101     |     14.906 |      1.142 |     14.225 |     25.685
     HttpParserBench.FullRequestRb     | Instructions Retired  |    101     | 1.462E+008 | 4.444E+006 | 1.456E+008 | 1.904E+008
     HttpParserBench.FullRequestRb     | Branch Mispredictions |    101     |   8597.545 |  32944.192 |   4096.000 | 3.359E+005
     HttpParserBench.FullRequestRb     | Cache Misses          |    101     |   7340.356 |  19205.976 |      0.000 | 1.966E+005
     HttpParserBench.FullRequestRob    | Duration              |    101     |     11.449 |      1.016 |     10.570 |     19.461
     HttpParserBench.FullRequestRob    | Instructions Retired  |    101     | 1.121E+008 | 4.019E+006 | 1.115E+008 | 1.521E+008
     HttpParserBench.FullRequestRob    | Branch Mispredictions |    101     |   5637.069 |  27954.121 |      0.000 | 2.826E+005
     HttpParserBench.FullRequestRob    | Cache Misses          |    101     |   9327.525 |  23771.758 |      0.000 | 2.417E+005
     HttpParserBench.HeadersRb         | Duration              |    101     |     19.093 |      0.387 |     18.369 |     20.433
     HttpParserBench.HeadersRb         | Instructions Retired  |    101     | 2.154E+008 |  99980.196 | 2.152E+008 | 2.156E+008
     HttpParserBench.HeadersRb         | Branch Mispredictions |    101     |  15167.366 |   1968.174 |  12288.000 |  20480.000
     HttpParserBench.HeadersRb         | Cache Misses          |    101     |   7259.248 |   2830.759 |   4096.000 |  16384.000
     HttpParserBench.HeadersRob        | Duration              |    101     |     14.984 |      2.853 |     13.532 |     41.352
     HttpParserBench.HeadersRob        | Instructions Retired  |    101     | 1.702E+008 | 3.744E+006 | 1.695E+008 | 2.073E+008
     HttpParserBench.HeadersRob        | Branch Mispredictions |    101     |   7259.248 |  26181.619 |      0.000 | 2.662E+005
     HttpParserBench.HeadersRob        | Cache Misses          |    101     |  10138.614 |  18414.644 |   4096.000 | 1.843E+005
     HttpParserBench.HeadersRobRef     | Duration              |    101     |     13.530 |      0.606 |     12.602 |     16.314
     HttpParserBench.HeadersRobRef     | Instructions Retired  |    101     | 1.601E+008 | 1.101E+005 | 1.599E+008 | 1.608E+008
     HttpParserBench.HeadersRobRef     | Branch Mispredictions |    101     |   4298.772 |   2118.566 |      0.000 |  16384.000
     HttpParserBench.HeadersRobRef     | Cache Misses          |    101     |   6448.158 |   3679.409 |   4096.000 |  20480.000
     HttpParserBench.RequestLineRb     | Duration              |    101     |      8.992 |      0.604 |      8.176 |     12.394
     HttpParserBench.RequestLineRb     | Instructions Retired  |    101     | 7.180E+007 | 1.461E+006 | 7.130E+007 | 8.630E+007
     HttpParserBench.RequestLineRb     | Branch Mispredictions |    101     |   5150.416 |  17699.777 |      0.000 | 1.802E+005
     HttpParserBench.RequestLineRb     | Cache Misses          |    101     |   5434.297 |   5216.861 |      0.000 |  49152.000
     HttpParserBench.RequestLineRob    | Duration              |    101     |      8.064 |      1.015 |      7.289 |     15.555
     HttpParserBench.RequestLineRob    | Instructions Retired  |    101     | 5.745E+007 | 3.204E+006 | 5.700E+007 | 8.930E+007
     HttpParserBench.RequestLineRob    | Branch Mispredictions |    101     |   6813.149 |  31120.314 |      0.000 | 3.154E+005
     HttpParserBench.RequestLineRob    | Cache Misses          |    101     |   6732.040 |  17315.805 |      0.000 | 1.720E+005

### CODE REVIEW

**Comment by benaadams** [comment]
Up the iterations? 101 seems small?

**Comment by benaadams** [comment]
e.g. Legacy has a high max which will pull up the average, not sure the benchmark discards the jit

**Comment by KrzysztofCwalina** [comment]
It's actually 101 * 10K * unrolled loop (~10) = ~10M parses. i.e. The 101 is from "outer iterations"

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
