### PR TITLE
Update README build instructions

### PR DESCRIPTION
**Pull request by mellinoe**
Add some more specific instructions for building the projects in this repository.

### CODE REVIEW

**Comment by mellinoe** [comment]
This should kick off a CI run.

**Comment by mellinoe** [comment]
Hmm, something seems to be wrong with any of the tests using System.Slices. I think that the re-writing step isn't working properly, but I can't repro the issue locally. All of the test failures seem to indicate that the postcompile script didn't complete correctly. Investigating now and trying to get a repro...

**Comment by omariom** [comment]
@mellinoe 
Look at this issue https://github.com/dotnet/corefxlab/issues/620

**Comment by mellinoe** [comment]
Thanks for the hint, @omariom . It looks like those tools only work when run from a VS Developer Command Prompt... In the meantime I may try to get the CI jobs to run that command before running the build script. They were doing it previously.

**Comment by mellinoe** [comment]
Going to open a different PR, this description isn't accurate now.

**Pull request closed without merging**
