### PR TITLE
Remove unncessary stackalloc

### PR DESCRIPTION
**Pull request by davidfowl**
This *should* be fine AFAIK.

/cc @jkotas

### CODE REVIEW

**Comment by benaadams** [comment]
Is also this https://github.com/dotnet/coreclr/issues/8542

**Comment by davidfowl** [comment]
@benaadams yas, though I didn't look at the before and after

**Comment by benaadams** [comment]
Well its a PR that hasn't be taken...

**Comment by KrzysztofCwalina** [comment]
Ah, the power of spans.

**Pull request merged**
