### PR TITLE
Fixing the package script to not fail totally on one failure

### PR DESCRIPTION
**Pull request by sokket**
Fixing the package script to not fail totally on one failure

@KrzysztofCwalina

### CODE REVIEW

**Comment by sokket** [comment]
After this, the branch should be in a good, stable state where our daily builds pass every day again :)

**Comment by KrzysztofCwalina** [comment]
looks good.

**Comment by sokket** [comment]
This file does not interact with the build or build process at all so it should be fine to merge without a build

**Comment by KrzysztofCwalina** [comment]
@sokket, have you started a nightly to push the packages to myget?

**Comment by sokket** [comment]
Yes, build is in progress right now

**Comment by KrzysztofCwalina** [comment]
@sokket, Thanks!

**Pull request merged**
