### PR TITLE
Dropping to a lower version of CLI where perf tests work.

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @KrzysztofCwalina, @shiftylogic, @jorive, @livarcocc, @jkotas 

I am not sure what the cause is, but cli versions after 2.0.0-preview1-005760 produces no results from benchmark tests.

From @jorive: There was also a coreclr bug recently that broke capturing data over a week ago, which was reverted on April 14. 

I am not sure if this is related or not.

`D:\GitHub\Fork\corefxlab\scripts\PerfHarness>..\..\dotnet\dotnet.exe run -c Release --assembly System.Text.Primitives.Tests --perf:typenames System.Text.Primitives.Tests.EncodingPerfComparisonTests`

**Expected output (cli version 2.0.0-preview1-005760):**
[4/19/2017 6:25:29 PM][INF] Running 6 Benchmarks out of 6 Xunit Facts...
[4/19/2017 6:25:29 PM][INF]   System.Text.Primitives.Tests.EncodingPerfComparisonTests.EncodingPerformanceTestUsingCorefxlab(charLength: 1000, minCodePoint: 128, maxCodePoint: 2047)
...
[4/19/2017 6:25:29 PM][INF] Finished 6 tests in 0.357s (0 failed, 0 skipped)
[4/19/2017 6:25:31 PM][INF] ETW Tracing Session saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012528-System.Text.Primitives.Tests.etl"
[4/19/2017 6:25:32 PM][INF] Performance results saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012528-System.Text.Primitives.Tests.xml"
[4/19/2017 6:25:32 PM][INF] Markdown file saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012528-System.Text.Primitives.Tests.md"

     Test Name                                                                                                                                                 | Metric                | Iterations | AVERAGE |  STDEV.S |   MIN |       MAX
    :--------------------------------------------------------------------------------------------------------------------------------------------------------- |:--------------------- |:----------:| -------:| --------:| -----:| ---------:
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.EncodingPerformanceTestUsingCoreCLR(charLength: 1000, minCodePoint: 0, maxCodePoint: 127)        | Duration              |    1001    |   0.001 |    0.001 | 0.001 |     0.019
     System.Text.Primitives.Tests.EncodingPerfComparisonTests.EncodingPerformanceTestUsingCoreCLR(charLength: 1000, minCodePoint: 0, maxCodePoint: 127)        | Branch Mispredictions |    1001    |   0.000 |    0.000 | 0.000 |     0.000
...

**Actual output (cli version 2.0.0-preview1-005817):**
[4/19/2017 6:28:29 PM][INF] Running 6 Benchmarks out of 6 Xunit Facts...
...
[4/19/2017 6:28:29 PM][INF] Finished 6 tests in 0.357s (0 failed, 0 skipped)
[4/19/2017 6:28:31 PM][INF] ETW Tracing Session saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012828-System.Text.Primitives.Tests.etl"
[4/19/2017 6:28:31 PM][INF] Performance results saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012828-System.Text.Primitives.Tests.xml"
[4/19/2017 6:28:32 PM][INF] Markdown file saved to "D:\GitHub\Fork\corefxlab\scripts\PerfHarness\20170420012828-System.Text.Primitives.Tests.md"

     Test Name | Metric | Iterations | AVERAGE | STDEV.S | MIN | MAX
    :--------- |:------ |:----------:| -------:| -------:| ---:| ---:

### CODE REVIEW

**Comment by ahsonkhan** [comment]
**D:\Other\dotnet-5760>dotnet.exe --info**
.NET Command Line Tools (2.0.0-preview1-005760)

Product Information:
 Version:            2.0.0-preview1-005760
 Commit SHA-1 hash:  20207e1def

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Other\dotnet-5760\sdk\2.0.0-preview1-005760\

**D:\Other\dotnet-5764>dotnet.exe --info**
.NET Command Line Tools (2.0.0-preview1-005764)

Product Information:
 Version:            2.0.0-preview1-005764
 Commit SHA-1 hash:  0d57d7169f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Other\dotnet-5764\sdk\2.0.0-preview1-005764\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-001957-00
  Build    : f1a36d5c635c7b7950ddb641c50a9cef1b492e52

**Comment by ahsonkhan** [comment]
> **From @livarcocc:**  there were two changes between the two: one about which env variable the host uses to find the runtime package store (DOTNET_SHARED_STORE) and the other an update to the runtime to version 2.0.0-preview1-001960
so, yeah, I imagine your problem is in the runtime, somewhere between corefx and coreclr

@gkhanna79, @jkotas - is there a known issue that arose recently in the runtime regarding getting xunit perf benchmark results?

**Comment by gkhanna79** [comment]
There is no way to determine such an impact - you will need to investigate the failure to conclude it so.

**Comment by ahsonkhan** [comment]
>  you will need to investigate the failure to conclude it so

Do you have any recommendations on where to start? I am trying to filter out already known issues that might get fixed over the next few days. If that is true, we could just wait for the newest version that have the issue resolved. If you are not aware of any such issues, then I will dig deeper. I am surprised only we see this issue though. What other repos use xunit perf (and dotnet cli)?

**Comment by jorive** [comment]
@ahsonkhan 
This [issue](https://github.com/dotnet/coreclr/issues/11009) broke getting event source measurements on coreclr/corefx about 10 days ago.

**Pull request merged**
