### PR TITLE
Improved Pooling

### PR DESCRIPTION
**Pull request by benaadams**
Pool `BufferSegment`s
Add `ThreadStatic` single cache for `MemoryPool`
Test for negative `MemoryPool` block size request
Don't test `block.Slab != null` as its always true
Tidy up `MemoryPool`  `#if`

/cc @pakrym @davidfowl

### CODE REVIEW

**Comment by pakrym** [comment]
I did segment pool inside Pipe once (had an array per pipe) and it dropped throughput. Would be interesting how this does in benchmark.

**Comment by benaadams** [comment]
Some rough edges with unowned buffers am working through; shame test explore is soooooo slow

**Comment by KodrAus** [comment]
:+1: This won't affect my effort for an inheritable `MemoryPool`.

**Comment by davidfowl** [comment]
@benaadams where are the measurements, what did it actually improve?

**Comment by benaadams** [comment]
Is better but tracking down a bug that it causes in `RequestParsingBenchmark.PipelinedLiveAspNet`

**Comment by benaadams** [comment]
Is better but tracking down a bug that it causes in `RequestParsingBenchmark.PipelinedLiveAspNet` when crossing blocks

**Comment by benaadams** [comment]
Might be bug in parser

**Comment by benaadams** [comment]
Still haven't worked out if this is highlighting a bug or causing bug  😢

**Comment by benaadams** [comment]
Was dumb bug in my changes

**Comment by benaadams** [comment]
Pre
```
                        Method |      Mean     |    StdDev  |       Op/s | Scaled | Allocated |
------------------------------ |-------------- |----------- | ---------- |------- |---------- |
          PlaintextTechEmpower | 1.2338 us     | 0.0171 us  |  810530.58 |   1.00 |     349 B |
          PlaintextAbsoluteUri | 2.5928 us     | 0.0477 us  |  385676.71 |   2.10 |     692 B |
 PipelinedPlaintextTechEmpower | 1.0302 us     | 0.0071 us  |  970662.88 |   0.84 |     348 B |
                    LiveAspNet | 2.6340 us     | 0.0350 us  |  379646.25 |   2.14 |   1.07 kB |
           PipelinedLiveAspNet | 2.3953 us     | 0.0231 us  |  417492.29 |   1.94 |   1.07 kB |
                       Unicode | 4.6016 us     | 0.0696 us  |  217316.11 |   3.73 |   1.85 kB |
              UnicodePipelined | 4.4633 us     | 0.0262 us  |  224047.77 |   3.62 |   1.86 kB |
```
Post
```
                        Method |          Mean |     StdDev |       Op/s | Scaled | Allocated |
------------------------------ |-------------- |----------- |----------- |------- |---------- |
          PlaintextTechEmpower | 1,173.4917 ns | 17.7260 ns |  852157.75 |   1.00 |     343 B |
          PlaintextAbsoluteUri | 2,604.7020 ns | 51.3328 ns |  383921.07 |   2.22 |     686 B |
 PipelinedPlaintextTechEmpower |   986.3448 ns | 12.9587 ns | 1013844.29 |   0.84 |     343 B |
                    LiveAspNet | 2,532.4551 ns | 50.1321 ns |  394873.74 |   2.16 |   1.05 kB |
           PipelinedLiveAspNet | 2,420.5796 ns | 52.5500 ns |  413124.20 |   2.06 |   1.06 kB |
                       Unicode | 4,438.4725 ns | 70.0961 ns |  225302.74 |   3.78 |   1.83 kB |
              UnicodePipelined | 4,464.6126 ns | 90.8148 ns |  223983.60 |   3.81 |   1.85 kB |
```

Doing some further profiling

**Comment by benaadams** [comment]
dev
```
                        Method |          Mean |    StdDev  |       Op/s | Scaled | Allocated |
------------------------------ |-------------- |----------  |----------- |------- |---------- |
          PlaintextTechEmpower | 1,202.8000 ns | 0.0146 us  |  831380.06 |   1.00 |     349 B |
          PlaintextAbsoluteUri | 2,595.2000 ns | 0.0445 us  |  385332.00 |   2.16 |     692 B |
 PipelinedPlaintextTechEmpower | 1,008.7000 ns | 0.0081 us  |  991376.59 |   0.84 |     348 B |
                    LiveAspNet | 2,546.9000 ns | 0.0074 us  |  392640.16 |   2.12 |   1.07 kB |
           PipelinedLiveAspNet | 2,354.7000 ns | 0.0105 us  |  424682.77 |   1.96 |   1.07 kB |
                       Unicode | 4,625.7000 ns | 0.0856 us  |  216182.09 |   3.85 |   1.85 kB |
              UnicodePipelined | 4,476.7000 ns | 0.0828 us  |  223380.28 |   3.72 |   1.86 kB |
```
PR
```
                        Method |          Mean |     StdDev |       Op/s | Scaled | Allocated |
------------------------------ |-------------- |----------- |----------- |------- |---------- |
          PlaintextTechEmpower | 1,173.1428 ns | 28.0829 ns |  852411.15 |   1.00 |     343 B |
          PlaintextAbsoluteUri | 2,619.0268 ns | 71.5352 ns |  381821.22 |   2.23 |     686 B |
 PipelinedPlaintextTechEmpower |   983.2569 ns |  3.3094 ns | 1017028.18 |   0.84 |     343 B |
                    LiveAspNet | 2,464.9803 ns | 10.4459 ns |  405682.75 |   2.10 |   1.05 kB |
           PipelinedLiveAspNet | 2,446.4056 ns | 13.2502 ns |  408762.96 |   2.09 |   1.06 kB |
                       Unicode | 4,371.0052 ns | 57.3967 ns |  228780.33 |   3.73 |   1.83 kB |
              UnicodePipelined | 4,451.1854 ns | 54.0985 ns |  224659.25 |   3.80 |   1.85 kB |
```

**Comment by ahsonkhan** [comment]
@benaadams, can you resolve the conflicts?

@davidfowl, @pakrym, is this PR good to go?

**Comment by davidfowl** [comment]
We're avoiding churn right now

**Pull request closed without merging**
