### PR TITLE
Updating perf harness for running benchmark tests

### PR DESCRIPTION
**Pull request by ahsonkhan**
You should now be able to specify which performance tests you want to run, based on the class type name.

I added an extra option to pass in the assembly name as well to avoid extra console output for assemblies that do not contain that class type name.

**Example use:**
dotnet run -c Release -- --assembly Benchmarks --perf:typenames BytesReaderBench

image

**If you want to run all benchmark tests of certain types found in any of the assemblies, run:**
dotnet run -c Release --  --perf:typenames name1 [name2] [...]

image

**If you want to run all the benchmark tests in all assemblies, run:**
dotnet run -c Release

**xunit.performance.core version 1.0.0-alpha-build0048 contains the following:**
image

**Note:**
I was tired of seeing all the warnings so I disabled them: CS1701
We probably want to investigate at some point and fix them.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @KrzysztofCwalina @jorive

**Comment by davidfowl** [comment]
> I was tired of seeing all the warnings so I disabled them: CS1701

I wouldn't disable them without at least understanding why they are there. Why are they there?

**Comment by KrzysztofCwalina** [comment]
Could you also add the instructions to https://github.com/dotnet/corefxlab/blob/master/scripts/PerfHarness/README.md? Thanks.

**Comment by ahsonkhan** [comment]
> I wouldn't disable them without at least understanding why they are there. Why are they there?

I am not sure how to resolve this issue. As far as I can tell there is a mismatch of System.Runtime versions. I will file an issue. I tried to resolve them by matching up the xunit.performance.api versions and matching xunit to a version that xunit.performance.api [depends ](https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.xunit.performance) on, but it did not help. These warnings appear in building the rest of the corefxlab solution as well, for example:
25>PrimitiveParserIntegerTests.cs(1124,22,1124,70): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Text.Primitives' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy


> Assuming assembly reference "Assembly Name 1" matches "Assembly Name 2", you may need to supply runtime policy
The two assemblies differ in release and/or version number. For unification to occur, you must specify directives in the application's .config file, and you must provide the correct strong name of an assembly, as demonstrated in the following example code.

https://msdn.microsoft.com/en-us/library/2h4x8b08.aspx

CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Memory' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [D:\GitHub\Fork\corefxlab\tests\System.Slices.Tests\System.Slices.Tests.csproj]
CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Slices' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [D:\GitHub\Fork\corefxlab\tests\System.Slices.Tests\System.Slices.Tests.csproj]
MemoryTests.cs(246,34): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Slices' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [D:\GitHub\Fork\corefxlab\tests\System.Slices.Tests\System.Slices.Tests.csproj]
MemoryTests.cs(232,26): warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'System.Slices' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [D:\GitHub\Fork\corefxlab\tests\System.Slices.Tests\System.Slices.Tests.csproj]
CSC : warning CS1701: Assuming assembly reference 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'xunit.core' matches identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Runtime', you may need to supply runtime policy [D:\GitHub\Fork\corefxlab\tests\System.Slices.Tests\System.Slices.Tests.csproj]

...

**Comment by ahsonkhan** [comment]
> I wouldn't disable them without at least understanding why they are there. Why are they there?

Turns out, warning CS1701 was always suppressed.
However, our <NoWarn> property was squashing the list of warnings to ignore set within Microsoft.Net.SDK.CSharp.props.

The right way to add to the NoWarn list would be to append, like this:
https://github.com/dotnet/corefxlab/blob/2eee4ff79dd6e5c08f151e3daa612725594e1b49/samples/NetCoreSample/NetCoreXunitTestLibrary/NetCoreXunitTestLibrary.csproj#L23

@crummel 

I have removed all unnecessary <NoWarn> properties and adjusted the remaining to append rather than squash.

The same applies to <DefineConstants>. For example, this needs to be fixed, if it is relevant:
https://github.com/dotnet/corefxlab/blob/6c4cf54689003a5d8633370d3d14f2244237b9b7/src/System.Text.Formatting/GenerateCompatibilityTests/GenerateCompatibilityTests.csproj#L21

Thanks a lot for the help, @ericstj!

**Comment by KrzysztofCwalina** [comment]
looks good. thanks!

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina @mjp41 
I re-enable System.Slices.Tests (that were disabled a while back during the VS migration) and these two tests are failing. Can you please investigate?

> 15:35:40 Failed   System.Slices.Tests.MemoryTests.RacyAccess
15:35:40 Error Message:
15:35:40  Assert.False() Failure
15:35:40 Expected: False
15:35:40 Actual:   True
15:35:40 Stack Trace:
15:35:40    at System.Slices.Tests.MemoryTests.RacyAccess() in D:\j\workspace\Debug_prtestf5b6dea6\tests\System.Slices.Tests\MemoryTests.cs:line 109
15:35:40 Failed   System.Slices.Tests.MemoryTests.ArrayMemoryLifetime
15:35:40 Error Message:
15:35:40  Assert.Throws() Failure
15:35:40 Expected: typeof(System.InvalidOperationException)
15:35:40 Actual:   (No exception was thrown)
15:35:40 Stack Trace:
15:35:40    at System.Slices.Tests.MemoryTests.ArrayMemoryLifetime() in D:\j\workspace\Debug_prtestf5b6dea6\tests\System.Slices.Tests\MemoryTests.cs:line 60

**Comment by ahsonkhan** [comment]
@shiftylogic

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina  good to merge?

**Comment by KrzysztofCwalina** [comment]
yes. thanks. I will update the skipped test

**Comment by ahsonkhan** [comment]
Partially fixes #1155

**Pull request merged**
