### PR TITLE
Slice: Fixed possible overflow in EnumeratorObject.MoveNext method.

### PR DESCRIPTION
**Pull request by omariom**
- Fixed possible overflow in EnumeratorObject.MoveNext introduced while optimizing enumerators.
    See @VSadov's [comment](https://github.com/dotnet/corefxlab/pull/607/files#r52395716)
- Deleted Span.SpanEnumerator. Span now uses ReadOnlySpan's enumerators.

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Comment by omariom** [comment]
@dotnet-bot test this please

**Comment by omariom** [comment]
@KrzysztofCwalina 

:tada:

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
