### PR TITLE
Fixing up packages to not reference specific fxlab project versions

### PR DESCRIPTION
**Pull request by sokket**
Fixing up packages to not reference specific fxlab project versions

### CODE REVIEW

**Comment by livarcocc** [comment]
LGTM.

**Comment by sokket** [comment]
Looks like we have some dependency problems with RC...looking now

**Comment by sokket** [comment]
I've updated our project.json files to remove beta dependencies and remove corefxlab-specific version dependencies. Also disabled some failing HTTP tests after the project.json updates.

**Comment by sokket** [comment]
@dotnet-bot  test this please

**Pull request merged**
