### PR TITLE
Change namespace to Microsoft.Data.Analysis

### PR DESCRIPTION
**Pull request by pgovind**
Change the namespace to Microsoft.Data.Analysis
Also change the folder names and update the sln file to use the new paths
Also change the modifier for strings.resx to internal

### CODE REVIEW

**Comment by eerhardt** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

You still have a .csproj file in the `Microsoft.Data` folder. It should be deleted.

---
Refers to: src/Microsoft.Data/Microsoft.Data.Analysis.DataFrame.csproj:1 in 954e37f. [](commit_id = 954e37fa4c36e250059771421af8d1e88bed4a49, deletion_comment = False)

**Comment by eerhardt** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

This file (and package and .dll) should be named `Microsoft.Data.Analysis.csproj`. We have more types in here than just `DataFrame`. We shouldn't be putting the type name in the package name. If we did that, when we wanted to add a new type, we would be forced to add a whole new package.

---
Refers to: src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.DataFrame.csproj:1 in 954e37f. [](commit_id = 954e37fa4c36e250059771421af8d1e88bed4a49, deletion_comment = False)

**Comment by eerhardt** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

This file should be deleted.

---
Refers to: tests/Microsoft.Data.DataFrame.Tests/Microsoft.Data.DataFrame.Tests.csproj:1 in 954e37f. [](commit_id = 954e37fa4c36e250059771421af8d1e88bed4a49, deletion_comment = False)

**Comment by pgovind** [comment]
Rebased on master

**Comment by eerhardt** [comment]
> <Project Sdk="Microsoft.NET.Sdk">

This file should be named `Microsoft.Data.Analysis.Tests.csproj`. It shouldn't nave `.DataFrame` in it.

---
Refers to: tests/Microsoft.Data.Analysis.Tests/Microsoft.Data.Analysis.DataFrame.Tests.csproj:1 in e6d6019. [](commit_id = e6d6019961f51052f57df081babd8d417d773848, deletion_comment = False)

**Pull request merged**
