### PR TITLE
Responded to API review feedback 

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
- Renamed Position to SequencePosition
- Removed "cursor" terminology from public surface area
- Renamed VirtualIndex to RunningIndex

cc: @davidfowl, @pakrym, @terrajobst, @weshaggard, @steveharter, @joshfree

### CODE REVIEW

**Comment by pakrym** [comment]
https://github.com/dotnet/corefxlab/pull/2052

**Comment by pakrym** [comment]
Do we want to go through with ISequence review before renaming `Position`?

**Comment by davidfowl** [comment]
I think that makes sense. It's strange for these APIs to exist outside of the ISequence interface without the review.

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
> Do we want to go through with ISequence review before renaming Position?

We are running out of time. I wanted to start adding the immediate needs of pipelines (e.g. Position) to corfx this week. For this we need to settle on the name. I don't think ISequence will be settled on this (or next) week.

**Comment by pakrym** [comment]
I don't like the name `SequencePosition` it's even less obvious when used in regards to buffers and sounds like something from Unicode.

**Comment by KrzysztofCwalina** [comment]
I am not married to this name. What name[s] would you like?

**Comment by pakrym** [comment]
`ReadCursor`, `Position`, `Cursor`

**Comment by KrzysztofCwalina** [comment]
I think the feedback from the review was that the type should not be using a very generic name that can clash with existing types. So Cursor and Position are no good. 

ReadCursor is a really bad name. The type has very little to do with "reading". 

I am not sure why SequencePosition "sounds like something from Unicode." Can you point me to the part of the Unicode that talks about sequence positions?

Also, if we ever add ```ISequence<T>``` to the platfrom, it would be good if the position type worked well with it, namewise.

Lastly, if you feel we are not close to closing on the name, I will close this PR and we can talk more on Friday. We can merge your other PR that changes the VirtualIndex and "cursor" usage.

**Comment by pakrym** [comment]
Maybe UTF thing is just my interpretation. But I would really like something that sounds a bit less alien when used with buffers and bytes.

**Comment by KrzysztofCwalina** [comment]
Closing as we will merge some of these changes as part of another PR. We will close on the name for Position separately.

**Pull request closed without merging**
