### PR TITLE
Reverting to a previous compiler version to try and fix the build errors

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @VSadov, @shiftylogic, @KrzysztofCwalina 

Essentially, reverting: https://github.com/dotnet/corefxlab/pull/1631

### CODE REVIEW

**Comment by VSadov** [comment]
This is reverting all the  way to pre-beta,

If https://github.com/dotnet/corefxlab/pull/1638 passes, we should revert to that one. Assuming that one does not have the race (or it is not as bad).

**Comment by VSadov** [comment]
https://github.com/dotnet/corefxlab/pull/1638 passed tests, I think we should revert to that one.

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test


@shiftylogic, @davidfowl, what should we do regarding this test that has been intermittently failing on Linux for a while?

mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_release_prtest/tests/System.IO.Pipelines.Tests/bin/Release/netcoreapp2.0/System.IO.Pipelines.Tests.dll(.NETCoreApp,Version=v2.0)
16:56:05 Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170502-03
16:56:05 Copyright (c) Microsoft Corporation.  All rights reserved.
16:56:05 
16:56:05 Starting test execution, please wait...
16:56:06 [xUnit.net 00:00:00.4840427]   Discovering: System.IO.Pipelines.Tests
16:56:07 [xUnit.net 00:00:01.1657019]   Discovered:  System.IO.Pipelines.Tests
16:56:07 [xUnit.net 00:00:01.3872187]   Starting:    System.IO.Pipelines.Tests
16:56:09 Ping: 500; Pong: 500; Time: 54ms
16:56:09 Ping: 500; Pong: 500; Time: 26ms
16:56:09 Ping: 500; Pong: 500; Time: 33ms
16:56:09 Ping: 500; Pong: 500; Time: 27ms
16:56:09 Ping: 500; Pong: 500; Time: 27ms
16:56:09 Ping: 500; Pong: 500; Time: 33ms
16:56:10 Ping: 500; Pong: 500; Time: 12ms
16:56:10 Ping: 500; Pong: 500; Time: 12ms
16:56:10 Ping: 500; Pong: 500; Time: 12ms
16:56:10 Ping: 500; Pong: 500; Time: 13ms
16:56:15 The active test run was aborted. Reason: Unhandled Exception: System.IO.Pipelines.Networking.Libuv.Interop.UvException: Error -16 EBUSY resource busy or locked
16:56:15    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowError(Int32 statusCode)
16:56:15    at System.IO.Pipelines.Networking.Libuv.Interop.UvLoopHandle.ReleaseHandle()
16:56:15    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
16:56:15    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
16:56:15    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:56:15 
16:56:15

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

Confirming with another test run that this compiler version passes CI.

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Pull request merged**
