### PR TITLE
Making the product build also generate nuget packages

### PR DESCRIPTION
**Pull request by sokket**
Making the product build also generate nuget packages

@KrzysztofCwalina @livarcocc

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
This just creates packages; it does not push them to nuget/myget. Correct?

**Comment by sokket** [comment]
Correct, the pack command only creates them. We will still need the VSO build to do the actual publishing, which I am working on now

**Comment by KrzysztofCwalina** [comment]
Looks good!

**Comment by sokket** [comment]
Jenkins looks to be down :(

**Comment by sokket** [comment]
@dotnet-bot test this please

**Comment by sokket** [comment]
@dotnet-bot test this please

**Comment by sokket** [comment]
@dotnet-bot test this please

**Comment by sokket** [comment]
Added an intermediate output directory to prevent build race conditions

**Pull request merged**
