### PR TITLE
Fix build for demo project LibuvWithNonAllocatingFormatters

### PR DESCRIPTION
**Pull request by alexanderkozlenko**

### CODE REVIEW

**Comment by alexanderkozlenko** [comment]
@dotnet-bot test Windows Debug

**Comment by KrzysztofCwalina** [comment]
Hmmm, I am not sure we want cross project references here. I wanted the demos to be test grounds for the nuget packages.

**Comment by alexanderkozlenko** [comment]
I used [QotdService.csproj](https://github.com/dotnet/corefxlab/blob/master/demos/QotdService/Service/QotdService.csproj) as a sample. If this approach is not good, [packages.config](https://github.com/dotnet/corefxlab/blob/master/demos/LibuvWithNonAllocatingFormatters/sample/packages.config) should be updated with correct package versions, because NuGet in VS doesn't recognize them.

**Comment by KrzysztofCwalina** [comment]
@alexanderkozlenko, btw, thanks for submitting this PR anyway. I will fix the demo. I just need to get the libuvwrapper working again. We recently broke it with all the changes to corefxlab build system.

**Pull request closed without merging**
