### PR TITLE
Updating use of AsSpan to Span property and rename AsMemory to Memory

### PR DESCRIPTION
**Pull request by ahsonkhan**
This supersedes and unblocks https://github.com/dotnet/corefxlab/pull/1787

cc @dotnet/corefxlab-contrib

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by KrzysztofCwalina** [comment]
looks good.

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test
@dotnet-bot test Innerloop Ubuntu16.04 Debug Build and Test
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Pull request merged**
