### PR TITLE
Adding TextEncoder overloads and splitting the classes into separate …

### PR DESCRIPTION
**Pull request by ahsonkhan**
…source files.

 - Cleaning up and addressing PR comments from the closed PR #1103 

As part of Issue #1091 - Productize Encoding APIs

### CODE REVIEW

**Comment by ahsonkhan** [comment]
I closed the previous PR because I pulled in commits from master, accidentally.

The changes here:
- split the Utf8 and Utf16 encoding classes into separate source files in the System.Text.Utf8 and System.Text.Utf16 namespaces
- removed the override methods for encoding string for both Utf8 and Utf16.
```C#
public override bool TryEncodeString(string value, Span<byte> buffer, out int bytesWritten)
```

**Comment by ahsonkhan** [comment]
cc @KrzysztofCwalina can this be merged?

**Comment by KrzysztofCwalina** [comment]
I am not sure which of these changes are new code and which are just the split. I would like to know that so I can review new code.

**Comment by ahsonkhan** [comment]
> I am not sure which of these changes are new code and which are just the split. I would like to know that so I can review new code.

The only difference is the removal of the TryEncodeString override methods, and the namespace change:

```C#
using System.Text.Utf8;
namespace System.Text.Utf16
{
...
namespace System.Text.Utf8 
{
```

The rest has remained unchanged from the previous PR.

**Comment by KrzysztofCwalina** [comment]
OK. In this case looks good.

**Pull request merged**
