### PR TITLE
Update build instructions in README.md

### PR DESCRIPTION
**Pull request by mellinoe**
This just updates the instructions again. Using this also to test CI.

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot Looks like CI didn't update immediately...

**Comment by mellinoe** [comment]
@dotnet-bot test this please

**Comment by mellinoe** [comment]
@dotnet-bot Test this, please

**Comment by mellinoe** [comment]
@dotnet-bot Test this, please

**Comment by mellinoe** [comment]
@dotnet-bot test ci please

**Comment by omariom** [comment]
@mellinoe 
When trying to open the solution I get 
"The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found."

Is it related to "This requires unreleased plugins to work at this point in time."?

**Pull request merged**
