### PR TITLE
Added Open Issues Section

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
cc @joshfree, @terrajobst

**Comment by joshfree** [comment]
@davidfowl did you have anything to add around the slow-span impl?

**Comment by joshfree** [comment]
@KrzysztofCwalina this is an OK list.  Did you want to seed the discussion on these by putting a stake in the ground on any of them?

**Comment by KrzysztofCwalina** [comment]
@joshfree, I will try. I really would like to put a stake in the ground for Memory\<T\> design, but I need some time to prototype.

**Pull request merged**
