### PR TITLE
Brotli Native Source Code Snapshot + Binaries

### PR DESCRIPTION
**Pull request by shiftylogic**
This is a temporary fix while we iron out the official story / details for getting Brotli native binaries from the google/Brotli repo.

There will be another check-in coming with binaries for osx and linux as well.

@ahsonkhan @KrzysztofCwalina @joshfree

### CODE REVIEW

**Comment by shiftylogic** [comment]
NOTE: the only code that is not from google/brotli is the script for building the windows binaries.

**Comment by joshfree** [comment]
@richlander do we need to update the root repo LICENSE.txt to reference the external/Brotli/LICENSE file as part of this change?

**Comment by KrzysztofCwalina** [comment]
This is a lot of code. It will stay in corfxlab history forever. Can we create a separate repo for it?

**Comment by ahsonkhan** [comment]
> the only code that is not from google/brotli is the script for building the windows binaries.

what is the file name for this script?

**Comment by shiftylogic** [comment]
build-windows.cmd

**Comment by shiftylogic** [comment]
Closing this and opening a new PR for just pushing the binaries.

**Pull request closed without merging**
