### PR TITLE
test [NO MERGE] [DO NOT RESTART THE FAILED TEST]

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
Innerloop Ubuntu16.04 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test Innerloop OSX10.12 Release Build and Test
@dotnet-bot test Innerloop OSX10.12 Debug Build and Test

**Comment by KrzysztofCwalina** [comment]
Please don't restart the failed test.

**Comment by jkotas** [comment]
problem understood

**Comment by joshfree** [comment]
> problem understood

What's the root cause?

**Comment by jkotas** [comment]
@joshfree BufferReader code is passing large struct by value:
- Good: This turned out to be a good stress test for the runtime that uncovered a bug: https://github.com/dotnet/coreclr/issues/16044 has more details and highly reliable repro.
- Bad: This is very inefficient. https://github.com/dotnet/corefxlab/pull/2097 has discussion about fixing it. It does not seem straightforward.

**Pull request closed without merging**
