### PR TITLE
Console fixes

### PR DESCRIPTION
**Pull request by terrajobst**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
One thing I wanted to do with the demo was to show that it's possible to pass command line args to the app. Maybe you could change the sample such that optionally people can pass in the size of the square?

But I think it's ok to check in as-is, if you don't have time to do it now.

**Comment by akoeplinger** [comment]
Where should I file the feature request for drawing a penguin on Linux and an apple on OSX :see_no_evil: :laughing:

**Comment by KrzysztofCwalina** [comment]
Maybe that should be the command line arg? :-)

**Comment by stephentoub** [comment]
If you go ahead and check this in, I'll add Tux :)

**Comment by terrajobst** [comment]
Go for it! It would be awesome to detect the OS and draw the appropriate ASCII art :-)

**Comment by KrzysztofCwalina** [comment]
Looks great

**Pull request merged**
