### PR TITLE
Add sample for porting to .NET Core

### PR DESCRIPTION
**Pull request by richlander**
/cc @Petermarcu, @weshaggard, @davidfowl, @martinwoodward

### CODE REVIEW

**Comment by Petermarcu** [comment]
Looks good!

**Comment by KrzysztofCwalina** [comment]
Rich, could you move this to the "demos" folder or rename the demos folder to "samples". After this commit, we now have two folders "demos" and "samples" that are for the same things. We should have one such folder.

**Comment by KrzysztofCwalina** [comment]
Also, it would be great if either the commit message or a readme file explained what this sample illustrate, i.e. most other samples in the demo folder as CoreCLR apps.

**Comment by davidfowl** [comment]
Can we add an xproj example?

**Pull request merged**
