### PR TITLE
Only run test that are failing on Linux, on Windows and Mac

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @shiftylogic, @pakrym, @davidfowl 

- Disabling the test on linux - issue #1687 
- Fixing so that previously marked #if Windows tests run on windows.

### CODE REVIEW

**Comment by shiftylogic** [comment]
Do we know why the tests are failing on Linux?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 Release Build and Test

**Comment by ahsonkhan** [comment]
> Do we know why the tests are failing on Linux?

I do not, which is why I filed the issue, so we can keep track of this and investigate. For now, I want to unblock our CI failures.

**Comment by ahsonkhan** [comment]
@shiftylogic, good to go?

**Comment by shiftylogic** [comment]
👍

**Pull request merged**
