### PR TITLE
Moving IndexOfVectorized (and tests) to SpanExtensions as part of cleanup

### PR DESCRIPTION
**Pull request by ahsonkhan**
Along with TryIndicesOf Span Extension methods.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Don't merge yet, please.

**Comment by ahsonkhan** [comment]
This can be merged now.

**Comment by davidfowl** [comment]
Go ahead 😄

**Comment by KrzysztofCwalina** [comment]
@benaadams submitted a PR to make IndexOf vectorized. If these two PR don't have too many conflicts, it's good to go.

**Comment by benaadams** [comment]
They shouldn't have any conflicts; though `IndexOfVectorized` will become superfluous once its worked its way though the build.

@KrzysztofCwalina Is also the "early exit" variant that probably wants adding here for when you have a long input and expect to find the result in the first several bytes?

**Comment by KrzysztofCwalina** [comment]
> @KrzysztofCwalina Is also the "early exit" variant that probably wants adding here for when you have a long input and expect to find the result in the first several bytes?

Yes. Last time I measured, if the buffer is long and the searched for item is in slot 0, the vectorized implementation was significantly slower (as in 10x slower).

**Pull request merged**
