### PR TITLE
Propagate channel exception from {WaitFor}Read/WriteAsync methods

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @davidfowl, @moozzyk, @anurse 

Discussed in https://github.com/aspnet/SignalR/pull/496

### CODE REVIEW

**Comment by davidfowl** [comment]
@stephentoub The Wait* methods never throw `ClosedChannelException` right?

**Comment by stephentoub** [comment]
They do with this change, wrapping the original. I could change that, but it a) seems like you want to indicate that the failure is because it was closed and then provide the details, and b) seemed odd to differ from Read/WriteAsync in whether the exception was wrapped. Don't feel strongly about it, though. I can see arguments either way, so if you'd prefer non-wrapped, I can change it.

**Comment by davidfowl** [comment]
I'd prefer if it didn't wrap the exception.

**Comment by anurse** [comment]
To be clear, given a normal `.TryComplete()` call (with no exception), the matching `.WaitToReadAsync()` calls will still **not** throw, right? It looks like that's still the case, just confirming.

Given that, I don't have a problem with this. I was just awaiting `.Completion` after my loops generally to avoid this, but it does seem a little counter-intuitive.

**Comment by stephentoub** [comment]
> given a normal .TryComplete() call (with no exception), the matching .WaitToReadAsync() calls will still not throw, right?

Correct

**Comment by ahsonkhan** [comment]
@davidfowl, @stephentoub, is this change good to go?

**Comment by stephentoub** [comment]
> is this change good to go?

No, I haven't re-updated it in response to the feedback.

**Pull request merged**
