### PR TITLE
Added WriteUInt32 to System.Binary

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
For now just UInt32. We will add more at some point.

### CODE REVIEW

**Comment by omariom** [comment]
Can it be implemented like this?
```C#
uint beValue = (ui >> 24) | (ui << 24) | ((ui >> 8) & 0x0000FF00) | ((ui << 8) & 0x00FF0000);
data.Write<UInt32>(beValue);
```

I tried it with the following code:
```C#
 uint ui = 0xDDCCBBAA;
 uint beUi = (ui >> 24) | (ui << 24) | ((ui >> 8) & 0x0000FF00) | ((ui << 8) & 0x00FF0000);
 Console.WriteLine("{0:X} => {1:X}", ui, beUi);
```
Output:
```
DDCCBBAA => AABBCCDD
```

**Comment by mellinoe** [comment]
I'm going to re-run the tests because I just merged my change to actually detect exit codes indicating failure.

@dotnet-bot test this please

**Comment by KrzysztofCwalina** [comment]
@omariom, good suggestion.

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Pull request merged**
