### PR TITLE
Removed operator+ from Position

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
cc: @ahsonkhan, @joshfree

### CODE REVIEW

**Comment by joshfree** [comment]
LGTM; did you want to add` int offset` overloads per the discussion this morning?

/cc @GrabYourPitchforks

**Comment by KrzysztofCwalina** [comment]
> did you want to addint offset overloads per the discussion this morning?

In general, we agreed that we might want to change the design (different names, location, etc.). But we don't yet have the perfect design. Yet, I wanted to remove operator+ asap as it has a correctness issue.

**Comment by pakrym** [comment]
https://github.com/dotnet/corefxlab/pull/2036

**Comment by pakrym** [comment]
What about all other things? Get, GetSegment, etc?

**Comment by KrzysztofCwalina** [comment]
@pakrym, I removed GetSegment. I can remove Get later this week.

**Comment by juliusfriedman** [comment]
Perfect is as perfect doze

**Pull request merged**
