### PR TITLE
Partial cleanup of SpanExtensionsLab

### PR DESCRIPTION
**Pull request by ahsonkhan**
Working towards - https://github.com/dotnet/corefxlab/issues/1314 / https://github.com/dotnet/corefxlab/issues/1292

- Move to System.Binary
    - public static T Read<T>(this ReadOnlySpan<byte> slice) where T : struct;
    - public static T Read<T>(this Span<byte> slice) where T : struct;
    - public static bool TryRead<T>(this ReadOnlySpan<byte> slice, out T value) where T : struct;
    - public static bool TryRead<T>(this Span<byte> slice, out T value) where T : struct;
    - public static bool TryWrite<T>(this Span<byte> slice, T value) where T : struct;
    - public static void Write<T>(this Span<byte> slice, T value) where T : struct;

- Moved to SpanExtensions: (PR https://github.com/dotnet/corefx/pull/17322)
    - public static bool StartsWith(this ReadOnlySpan<byte> bytes, ReadOnlySpan<byte> slice);
    - public static bool StartsWith<T>(this ReadOnlySpan<T> items, ReadOnlySpan<T> slice) where T : struct, IEquatable<T>;

- Move to BuffersExtension in experimental
    - ~public static int IndexOf(this ReadOnlySpan<byte> buffer, byte value0, byte value1);~
    - ~public static int IndexOf(this ReadOnlySpan<byte> buffer, byte value0, byte value1, byte value2);~
    - ~public static int IndexOf(this Span<byte> buffer, byte value0, byte value1);~
    - ~public static int IndexOf(this Span<byte> buffer, byte value0, byte value1, byte value2);~
    - public static int SequentialIndexOf(this ReadOnlySpan<byte> span, byte value);
    - public static int SequentialIndexOf(this Span<byte> span, byte value);
    - public static bool TryIndicesOf(this ReadOnlySpan<byte> buffer, byte value, Span<int> indices, out int numberOfIndices);
    - public static bool TryIndicesOf(this Span<byte> buffer, byte value, Span<int> indices, out int numberOfIndices);

- Remove (this should be on ArraySegment)
    - public static ArraySegment<T> Slice<T>(this ArraySegment<T> source, int count);

- Delete:
    - public static bool StartsWith(this ReadOnlySpan<char> str, ReadOnlySpan<char> value);

**NOTE:**
Moving the following to `System.Buffers.Experimental\System\Buffers\BufferExtensions.cs` causes `System.IO.Pipelines` to take a dependency on `System.Buffers.Experimental`.
```C#
    - public static int IndexOf(this ReadOnlySpan<byte> buffer, byte value0, byte value1);
    - public static int IndexOf(this ReadOnlySpan<byte> buffer, byte value0, byte value1, byte value2);
    - public static int IndexOf(this Span<byte> buffer, byte value0, byte value1);
    - public static int IndexOf(this Span<byte> buffer, byte value0, byte value1, byte value2);
```
The IndexOf with multiple byte values are used in `ReadCursorOperations.Seek`, here:
https://github.com/aspnet/KestrelHttpServer/blob/f6e5e74d9551df57effda19c856352608374cee7/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/KestrelHttpParser.cs#L273

This function is implemented here:
https://github.com/dotnet/corefxlab/blob/3bd0ffdef64b4510b408200cf4281d24b5742abd/src/System.IO.Pipelines/ReadCursorOperations.cs#L32

What should we do about this dependency? This is the only that System.IO.Pipelines depends on Buffers.Experimental.
If we remove those Seek overloads (and the one reference to it in kestrel), we could remove this dependency.

**Edit:**
Adding back IndexOf overloads to SpanExtensionsLab (in Buffes.Primitives). Will remove them once they are ported over to corefx (in System.Memory.dll).

### CODE REVIEW

**Comment by davidfowl** [comment]
> Moving the following to System.Buffers.Experimental\System\Buffers\BufferExtensions.cs causes System.IO.Pipelines to take a dependency on System.Buffers.Experimental.

I'm not a fan of this. Move those methods to corefx proper before breaking this package.

**Comment by KrzysztofCwalina** [comment]
Yeah, if the APIs are used by pipelines, and we know they have benefits, we should just have them in SpanExtensions. BTW, I think it would be ok to move the APIs to SpanExtensions without proving they have benefits (perf) and measure later.

**Comment by KrzysztofCwalina** [comment]
Looks good. Thanks!

**Comment by KrzysztofCwalina** [comment]
Ah, I think I merged Ben's rename and now there is a conflict. Could you please resolve and then just merge? Thanks.

**Comment by ahsonkhan** [comment]
@KrzysztofCwalina, resolved the conflicts.

**Pull request merged**
