### PR TITLE
Made ReadResult much smaller

### PR DESCRIPTION
**Pull request by benaadams**
In relation to  #1393

@davidfowl more like this?

### CODE REVIEW

**Comment by davidfowl** [comment]
@benaadams perf numbers?

**Comment by benaadams** [comment]
Pretty much the same

**Comment by benaadams** [comment]
Meh

Before
```
                                          Method |        Mean |    StdDev |          RPS |
------------------------------------------------ |------------ |---------- |------------- |
                         ParseLiveAspNetTwoTasks | 258.9510 ns | 3.2996 ns | 3,861,734.20 |
                           ParseLiveAspNetInline | 151.8228 ns | 9.6749 ns | 6,586,625.23 |
                          WritePlaintextResponse | 406.5889 ns | 4.8799 ns | 2,459,486.43 |
                      WriteSpanPlaintextResponse | 648.2650 ns | 9.5436 ns | 1,542,579.09 |
 WriteableBufferWriterWriteFastPlaintextResponse | 258.1190 ns | 3.3127 ns | 3,874,181.60 |
```

After
```
                                          Method |        Mean |     StdDev |          RPS |
------------------------------------------------ |------------ |----------- |------------- |
                         ParseLiveAspNetTwoTasks | 257.6774 ns |  1.6652 ns | 3,880,822.13 |
                           ParseLiveAspNetInline | 151.5543 ns |  4.7697 ns | 6,598,294.68 |
                          WritePlaintextResponse | 411.2078 ns | 13.2229 ns | 2,431,860.22 |
                      WriteSpanPlaintextResponse | 644.8925 ns |  5.4988 ns | 1,550,646.11 |
 WriteableBufferWriterWriteFastPlaintextResponse | 258.7212 ns |  3.6687 ns | 3,865,164.96 |
```

Going to run it again as they are crazy close

**Comment by benaadams** [comment]
Pretty much the same

**Pull request closed without merging**
