### PR TITLE
Misplaced double-quote

### PR DESCRIPTION
**Pull request by shiftylogic**
FYI, these changes are not noticeable until they are run by the VSO build system in most cases, thus the small tweaks.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
>  until they are run by the VSO build system in most cases

What was the error message in VSO before this change?

**Comment by shiftylogic** [comment]
Invoke-Expression : A positional parameter cannot be found that accepts argument 'GITHUB_USER=dotnet-bot'.

**Comment by ahsonkhan** [comment]
< 6 minutes for the CI to go green. Nice :)

**Comment by davidfowl** [comment]
What is this?

**Comment by ahsonkhan** [comment]
> What is this?

Related to https://github.com/dotnet/corefxlab/pull/1422

**Pull request merged**
